#!/bin/bash
#
# Copyright 2010 Jeremy Schneider
#
# This file is part of EC2-RAC-BUILDER.
#
# EC2-RAC-BUILDER is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EC2-RAC-BUILDER is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
#

[ -n "$DEBUG" ] && set -x

[ -z "$2" ] && { echo "Usage: init-network-node <instance-id> [ public | private ]" && exit 1; }
[ "$2" != "public" ] && [ "$2" != "private" ] && { echo "ERROR: unrecognized parameter '$2'" && exit 1; }

. $(dirname $0)/env

echo "ec2 load instance" >&2
DOUT="$(ec2din $1)"
ADDR=$(echo "$DOUT"|awk '/running/{print$4}')
while [ -z "$ADDR" ]; do
  [ -z "$(echo "$DOUT"|grep ^INSTANCE)" ] && echo "$DOUT" && echo "ERROR - can't find instance '$1'" && exit 1
  DOUT="$(ec2din $1)"
  ADDR=$(echo "$DOUT"|awk '/running/{print$4}')
done
echo "$DOUT"  

until curl -u vpncubed:$1 -k https://$ADDR:8000/ | grep "Upload runtime snapshot"; do echo "boot O.S." >&2; sleep 5; done

echo "configure switch" >&2
TOKEN=$(curl -u vpncubed:$1 -k -c /tmp/amazon/$1.cookie https://$ADDR:8000/snapshot | grep "authenticity_token"|sed 's/.*value="\(.*\)".*/\1/')
curl -u vpncubed:$1 -k -b /tmp/amazon/$1.cookie -F snapshot=@snapshot_$2.gz -F authenticity_token=$TOKEN https://$ADDR:8000/snapshot

until curl -u vpncubed:rac -k https://$ADDR:8000/status | grep "RAC-$2"; do echo "reboot O.S." >&2; sleep 5; done

